trigger:
  tags:
    include:
      - v*
  branches:
    include:
      - develop
      - release*
  paths:
    exclude:
      - README.md
pr: none

jobs:
  - job: Build_x86
    pool:
      vmImage: 'Ubuntu-16.04'

    steps:
      - template: pipeline.yaml
        parameters:
          arch: 'X86'
          repository: 'iofog/proxy'

  - job: Build_ARM
    pool: 'RPi'

    steps:
      - template: pipeline.yaml
        parameters:
          arch: 'ARM'
          repository: 'iofog/proxy-arm'
