trigger:
  tags:
    include:
      - v*
  branches:
    include:
      - develop
      - release*
  paths:
    exclude:
      - README.md
pr: none

variables:
  registry: 'Edgeworx DockerHub'
  imageTag:

stages:
  - stage: Preflight
    jobs:
      - job: Initialize_Variables
        pool:
          vmImage: 'Ubuntu-16.04'
        steps:
          - script: |
              if [[ $(Build.SourceBranch) == refs/tags* ]]; then
                TAG=$(echo $(Build.SourceBranch) | sed "s|refs/tags/v||g")
                echo "##vso[task.setvariable variable=imageTag]$TAG"
              else
                LATESTTAG=$(git tag | tail -1)
                LATESTVERS=${LATESTTAG#?}
                if [ -z "$LATESTVERS" ]; then LATESTVERS=0.0.0; fi
                echo "##vso[task.setvariable variable=imageTag]$LATESTVERS-b$(Build.BuildId)"
              fi
              echo $(imageTag)
            displayName: 'Set image tag'

  - stage: Build
    jobs:
      - job: Build_x86
        pool:
          vmImage: 'Ubuntu-16.04'

        steps:
          - template: pipeline.yaml
            parameters:
              arch: 'X86'
              repository: 'iofog/proxy'
              imageTag: $(imageTag))

      - job: Build_ARM
        pool: 'RPi'

        steps:
          - template: pipeline.yaml
            parameters:
              arch: 'ARM'
              repository: 'iofog/proxy-arm'
              imageTag: $(imageTag))
