trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
pr: none

variables:
  repository: 'iofog/proxy-dev'

jobs:
  - job: Build_x86
    pool:
      vmImage: 'Ubuntu-16.04'

    steps:
      - task: Docker@2
        displayName: 'build and push docker image'
        inputs:
          containerRegistry: 'Edgeworx DockerHub'
          repository: $(repository)
          command: 'buildAndPush'
          Dockerfile: 'Dockerfile.iofog'
          tags: |
            latest
  - job: Build_ARM
    pool: 'RPi'

    steps:
      - task: Docker@2
        displayName: 'build and push docker image'
        inputs:
          containerRegistry: 'Edgeworx DockerHub'
          repository: $(repository)-arm
          command: 'buildAndPush'
          Dockerfile: 'Dockerfile.iofog'
          tags: |
            latest