FROM registry.access.redhat.com/ubi9/nodejs-20-minimal:latest

ENV DEBUG=iofog
ENV LOGLEVEL=info

RUN mkdir -p /opt/app-root/
WORKDIR /opt/app-root/

ADD package.json /opt/app-root/
RUN npm install
COPY lib lib
COPY bin bin
COPY LICENSE /licenses/LICENSE

LABEL org.opencontainers.image.description=proxy
CMD ["node", "/opt/app-root/bin/iofog.js"]