parameters:
  - name: 'arch'
    type: string
    default: X86
  - name: 'repository'
    type: string

steps:
  - script: |
      if [[ $(ref) == refs/tags* ]]; then
        TAG=$(echo $(ref) | sed "s|refs/tags/v||g")
        echo "##vso[task.setvariable variable=imageTag]$TAG"
      else
        LATESTTAG=$(git tag | tail -1)
        LATESTVERS=${LATESTTAG#?}
        if [ -z "$LATESTVERS" ]; then LATESTVERS=0.0.0; fi
        echo "##vso[task.setvariable variable=imageTag]$LATESTVERS-b$(buildTag)"
      fi
    displayName: 'Set image tag'
  - script: |
      echo $(imageTag)
    displayName: 'Check image tag'

  - task: Docker@2
    displayName: 'build and push docker image'
    inputs:
      containerRegistry: 'Edgeworx GCP'
      repository: ${{ parameters.repository }}
      command: 'buildAndPush'
      Dockerfile: 'Dockerfile.iofog'
      tags: |
        $(Build.SourceBranchName)
        $(imageTag)
