parameters:
  - name: 'arch'
    type: string
    default: X86
  - name: 'repository'
    type: string

variables:
  registry: 'Edgeworx DockerHub'
  ref: $(Build.SourceBranch)
  imageTag:
  buildTag: $(Build.BuildId)
  branchTag: $(Build.SourceBranchName)

steps:
  - script: |
      if [[ $(ref) == refs/tags* ]]; then
        TAG=$(echo $(ref) | sed "s|refs/tags/v||g")
        echo "##vso[task.setvariable variable=imageTag]$TAG"
      else
        LATESTTAG=$(git tag | tail -1)
        LATESTVERS=${LATESTTAG#?}
        if [ -z "$LATESTVERS" ]; then LATESTVERS=0.0.0; fi
        echo "##vso[task.setvariable variable=imageTag]$LATESTVERS-b$(buildTag)"
      fi
      echo $(imageTag)
    displayName: 'Set image tag'

  - script: |
      echo "${{ parameters.repository }}:$(imageTag)" > ${{ parameters.arch }}_DOCKER_IMAGE
    displayName: 'Save Docker image name and tag to ${{ parameters.arch }}_DOCKER_IMAGE into artifacts'

  - task: CopyFiles@2
    inputs:
      SourceFolder: $(System.DefaultWorkingDirectory)
      TargetFolder: $(Build.ArtifactStagingDirectory)
      Contents: |
        ${{ parameters.arch }}_DOCKER_IMAGE
      OverWrite: true
    displayName: 'artefacts to publish'

  - task: Docker@2
    displayName: 'build and push docker image'
    inputs:
      containerRegistry: $(registry)
      repository: ${{ parameters.repository }}
      command: 'buildAndPush'
      Dockerfile: 'Dockerfile.iofog'
      tags: |
        $(imageTag)
        $(branchTag)

