---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tcp-echo-proxy
spec:
  selector:
    matchLabels:
      application: tcp-echo-proxy
  template:
    metadata:
      labels:
        application: tcp-echo-proxy
    spec:
      serviceAccountName: icproxy
      containers:
      - name: proxy
        env:
        - name: ICPROXY_CONFIG
          value: "amqp:echo=>tcp:9090,tcp:9090=>amqp:echo"
        - name: ICPROXY_POD_SELECTOR
          value: "application=tcp-echo"
        image: quay.io/skupper/icproxy
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: connect
          mountPath: "/etc/messaging/"
          readOnly: true
      volumes:
      - name: connect
        secret:
          secretName: myrouter
---
apiVersion: v1
kind: Service
metadata:
  name: echo
spec:
  ports:
  - port: 9090
    targetPort: 9090
  selector:
    application: tcp-echo-proxy
---
